name: Build and Deploy
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  repository_dispatch:
    types:
      - publish-event

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build
        env:
          CI: true
          NODE_ENV: production

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: out

      - name: Send toots
        run: npm run tootNewPosts
        env:
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}

      - name: Send butterflies
        run: npm run bskNewPosts
        env:
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
